### ISSUE TITLE
initial compilation error with the project

### ISSUE THREAD

**Issue by mvelicangil** [kpmiller/emulator101#18]
perhaps this is rather rudimentary yet these two missing file errors is what I am getting...

error: /Users/mvelicangil/Desktop/emulator_i8080_xcode/emulator101-master-3/CocoaPart3-Attract/Invaders/invaders.e: No such file or directory

and

error: /Users/mvelicangil/Desktop/emulator_i8080_xcode/emulator101-master-3/CocoaPart3-Attract/Invaders/invaders.f: No such file or directory

along with 
 
red alerts for invaders.h and invaders.g under the supporting files... 
where only main.m resides

**Comment by mvelicangil** [comment]
guess they are the rom files ... well let me do some digging around first... :)

**Comment by kpmiller** [comment]
Yes those are the ROM files that you have to find somewhere.
