### ISSUE TITLE
possible mistakes in 8080 reference

### ISSUE THREAD

**Issue by kpmiller** [kpmiller/emulator101#3]
Reported on disqus/twitter:

the reference for CALL specifies SP<-SP+2, but comparing with the JS emulator I believe it should actually be SP<-SP-2

Typo: 0x26 should be: "H <- byte 2"

**Comment by padremayi** [comment]
Hi, on my Intel 8080 reference (_8080 Microcomputer Systems User's Manual - September 1975_) I have
`(SP) <-- (SP) - 2`

**Comment by azisyus** [comment]
http://www.emulator101.com/reference/8080-by-opcode.html

http://nemesis.lonestar.org/computers/tandy/software/apps/m4/qd/opcodes.html

last one says `SP <- SP - 2` and according to this [commit](https://gitlab.com/azizyus/8080Emulator/commit/e71d0d3cb51176c70c1aaae0705f4ecd0af559f8), which is a 8080 emulator(based on emulator101) im woking on it right now, i didnt implement 0x26 yet but that opcode doesnt work before the loop i specified in output. 

the loop i was talkin about;

```
OPCODE => 0x5 PC =>6710 INSTRUCTION =>  ADDRESS => 8192 DCR B 
OPCODE => 0xc2 PC =>6711 INSTRUCTION =>  ADDRESS => 8192 JNZ adr 
OPCODE => 0x1a PC =>6706 INSTRUCTION =>  ADDRESS => 8192 LDAX D 
OPCODE => 0x77 PC =>6707 INSTRUCTION =>  ADDRESS => 8192 MOV M,A 
OPCODE => 0x23 PC =>6708 INSTRUCTION =>  ADDRESS => 8192 INX H 
OPCODE => 0x13 PC =>6709 INSTRUCTION =>  ADDRESS => 8192 INX D 
```

file just includes 256* loop and output until program gives exception and proves there is no 0x26 before that loop, i believe its `SP <- SP - 2`

[8080output.txt](https://github.com/kpmiller/emulator101/files/2663269/8080output.txt)

**Comment by azisyus** [comment]
@padremayi any suggestion after 8080 implementation? its very enjoyable side project

**Comment by padremayi** [comment]
> @padremayi any suggestion after 8080 implementation? its very enjoyable side project

After that you have to play the game! :P

I'm joking, I'll try to implement a Game Boy Color emulator, it seems that there are a lot of documents regarding its hardware

**Comment by kpmiller** [comment]
Updated web site, changed reference to CALL 0xCD.  The other thing mentioned looks like it is changed as described, although I don't remember doing it.
